Repository dhiemstra/esi, pull requests merged in 2018-02, with the labels that each got.

#4 Refactor caching
  README.md
  lib/esi.rb
  lib/esi/calls.rb
  lib/esi/client.rb
  lib/esi/version.rb
  test/cache_test.rb
  test/call_base_test.rb
  test/test_helper.rb
  test/version_test.rb
Labels: refactor

#12 #11 stabilize releases
  CHANGELOG.md
  esi.gemspec
Labels: pr-build-passing, pr-pending-review

#8 Eve savvy enhancements
  .gitignore
  .rubocop.yml
  Gemfile
  Rakefile
  bin/console
  esi.gemspec
  lib/esi.rb
  lib/esi/access_token.rb
  lib/esi/api_error.rb
  lib/esi/calls.rb
  lib/esi/client.rb
  lib/esi/o_auth.rb
  lib/esi/response.rb
  lib/esi/version.rb
  lib/omniauth/esi.rb
  lib/omniauth/strategies/esi.rb
  test/cache_test.rb
  test/call_base_test.rb
  test/client_test.rb
  test/test_helper.rb
  test/version_test.rb
Labels: enhancement, pr-build-passing, pr-pending-review

#10 Improvements
  esi.gemspec
  lib/esi/access_token.rb
  lib/esi/calls.rb
  lib/esi/calls/info.rb
  lib/esi/response.rb
  test/call_base_test.rb
Labels: pr-build-passing, pr-review-approved

#19 Add travis deploy configuration
  .travis.yml
Labels: pr-pending-review, task

#16 Restructure calls
  CHANGELOG.md
  lib/esi/api_error.rb
  lib/esi/calls.rb
  lib/esi/calls/alliances.rb
  lib/esi/calls/base.rb
  lib/esi/calls/characters.rb
  lib/esi/calls/corporations.rb
  lib/esi/calls/dogma.rb
  lib/esi/calls/fittings.rb
  lib/esi/calls/fleets.rb
  lib/esi/calls/industry.rb
  lib/esi/calls/info.rb
  lib/esi/calls/killmails.rb
  lib/esi/calls/markets.rb
  lib/esi/calls/route.rb
  lib/esi/calls/search.rb
  lib/esi/calls/ui.rb
  lib/esi/calls/universe.rb
  lib/esi/client.rb
Labels: pr-build-passing

#15 Cache key set
  lib/esi/calls.rb
  lib/esi/calls/base.rb
  test/call_base_test.rb
Labels: discussion, pr-build-passing, pr-review-approved, question, refactor
